(dolist (iter '(25 75))
  (let ((h (make-hash-table)))
    (dolist (n (mapcar #'parse-integer (uiop:split-string (uiop:read-file-string "11.input"))))
      (incf (gethash n h 0)))
    (dotimes (_ iter)
      (let ((x (make-hash-table)))
        (maphash (lambda (n c)
                   (cond
                     ((= n 0) (incf (gethash 1 x 0) c))
                     ((evenp (length (format nil "~A" n)))
                      (let ((s (format nil "~A" n))
                            (m (/ (length (format nil "~A" n)) 2)))
                        (incf (gethash (parse-integer (subseq s 0 m)) x 0) c)
                        (incf (gethash (parse-integer (subseq s m)) x 0) c)))
                     (t (incf (gethash (* n 2024) x 0) c))))
                 h)
        (setf h x)))
    (print (loop for v being the hash-values of h sum v))))
